name: Deploy Hugo site to Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'   # <--- 关键：拉取 submodule
          fetch-depth: 0
          persist-credentials: true

      - name: Ensure submodules initialized (fallback)
        run: |
          git submodule sync --recursive || true
          git submodule update --init --recursive || true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy (push built site to main)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: main
          keep_files: false
