name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main  # 当 main 分支有 push 时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 拉取仓库代码
      - name: Checkout
        uses: actions/checkout@v3

      # 安装 Hugo（extended 版本支持 SCSS）
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # 生成静态文件
      - name: Build
        run: hugo --minify

      # 部署到 GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages   # 生成文件推送到 gh-pages 分支
